package io.github.lingjiuu.event;

public enum UiEventType {
    RUN_STARTED,
    USER_MESSAGE,
    TURN_STARTED,
    ASSISTANT_TEXT_DELTA,
    REASONING_DELTA,
    TOKEN_USAGE,
    ASSISTANT_MESSAGE,
    TOOL_CALL,
    TOOL_EXECUTION_STARTED,
    TOOL_EXECUTION_UPDATE,
    TOOL_EXECUTION_FINISHED,
    TOOL_RESULT,
    APPROVAL_REQUESTED,
    APPROVAL_RESOLVED,
    CONTEXT_MESSAGE,
    FINAL_ANSWER,
    TURN_ABORTED,
    COMPACT_STARTED,
    COMPACT_FINISHED,
    COMPACT_SKIPPED,
    RUN_FINISHED,
    SESSION_RESET,
    ERROR
}
